version: '2'
services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    depends_on:
      - mongodb
    ports:
      - 3000:3000
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
